chore: update github definition (#31)
Was failing due to the zod schema's being output in sorted order and
referencing each other:

```
typescript-koa: src/api.github.com.yaml/schemas.ts(13399,11): error TS2448: Block-scoped variable 's_simple_user' used before its declaration.
typescript-koa: src/api.github.com.yaml/schemas.ts(13399,11): error TS2454: Variable 's_simple_user' is used before being assigned.
typescript-koa: src/api.github.com.yaml/schemas.ts(13400,14): error TS2448: Block-scoped variable 's_simple_user' used before its declaration.
typescript-koa: src/api.github.com.yaml/schemas.ts(13400,14): error TS2454: Variable 's_simple_user' is used before being assigned.
```

Fixed via #37