fix: array schema output order (#329)
previously the dependency graph didn't consider top-level array `items`
correctly, which meant you could have situations that resulted in errors
like:
```
 error TS2454: Variable 's_SomeArrayItems' is used before being assigned.
```