chore(deps): update all dependencies (#293)
This PR contains the following updates:

| Package | Change | Age | Adoption | Passing | Confidence | Type |
Update |
|---|---|---|---|---|---|---|---|
|
[@commander-js/extra-typings](https://redirect.github.com/commander-js/extra-typings)
| [`^12.1.0` ->
`^13.0.0`](https://renovatebot.com/diffs/npm/@commander-js%2fextra-typings/12.1.0/13.0.0)
|
[![age](https://developer.mend.io/api/mc/badges/age/npm/@commander-js%2fextra-typings/13.0.0?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![adoption](https://developer.mend.io/api/mc/badges/adoption/npm/@commander-js%2fextra-typings/13.0.0?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![passing](https://developer.mend.io/api/mc/badges/compatibility/npm/@commander-js%2fextra-typings/12.1.0/13.0.0?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![confidence](https://developer.mend.io/api/mc/badges/confidence/npm/@commander-js%2fextra-typings/12.1.0/13.0.0?slim=true)](https://docs.renovatebot.com/merge-confidence/)
| dependencies | major |
| [@typespec/compiler](https://typespec.io)
([source](https://redirect.github.com/microsoft/typespec)) | [`^0.62.0`
->
`^0.63.0`](https://renovatebot.com/diffs/npm/@typespec%2fcompiler/0.62.0/0.63.0)
|
[![age](https://developer.mend.io/api/mc/badges/age/npm/@typespec%2fcompiler/0.63.0?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![adoption](https://developer.mend.io/api/mc/badges/adoption/npm/@typespec%2fcompiler/0.63.0?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![passing](https://developer.mend.io/api/mc/badges/compatibility/npm/@typespec%2fcompiler/0.62.0/0.63.0?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![confidence](https://developer.mend.io/api/mc/badges/confidence/npm/@typespec%2fcompiler/0.62.0/0.63.0?slim=true)](https://docs.renovatebot.com/merge-confidence/)
| peerDependencies | minor |
| [@typespec/http](https://redirect.github.com/microsoft/typespec) |
[`^0.62.0` ->
`^0.63.0`](https://renovatebot.com/diffs/npm/@typespec%2fhttp/0.62.0/0.63.0)
|
[![age](https://developer.mend.io/api/mc/badges/age/npm/@typespec%2fhttp/0.63.0?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![adoption](https://developer.mend.io/api/mc/badges/adoption/npm/@typespec%2fhttp/0.63.0?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![passing](https://developer.mend.io/api/mc/badges/compatibility/npm/@typespec%2fhttp/0.62.0/0.63.0?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![confidence](https://developer.mend.io/api/mc/badges/confidence/npm/@typespec%2fhttp/0.62.0/0.63.0?slim=true)](https://docs.renovatebot.com/merge-confidence/)
| peerDependencies | minor |
| [@typespec/openapi](https://typespec.io)
([source](https://redirect.github.com/microsoft/typespec)) | [`^0.62.0`
->
`^0.63.0`](https://renovatebot.com/diffs/npm/@typespec%2fopenapi/0.62.0/0.63.0)
|
[![age](https://developer.mend.io/api/mc/badges/age/npm/@typespec%2fopenapi/0.63.0?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![adoption](https://developer.mend.io/api/mc/badges/adoption/npm/@typespec%2fopenapi/0.63.0?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![passing](https://developer.mend.io/api/mc/badges/compatibility/npm/@typespec%2fopenapi/0.62.0/0.63.0?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![confidence](https://developer.mend.io/api/mc/badges/confidence/npm/@typespec%2fopenapi/0.62.0/0.63.0?slim=true)](https://docs.renovatebot.com/merge-confidence/)
| peerDependencies | minor |
| [@typespec/openapi3](https://typespec.io)
([source](https://redirect.github.com/microsoft/typespec)) | [`^0.62.0`
->
`^0.63.0`](https://renovatebot.com/diffs/npm/@typespec%2fopenapi3/0.62.0/0.63.0)
|
[![age](https://developer.mend.io/api/mc/badges/age/npm/@typespec%2fopenapi3/0.63.0?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![adoption](https://developer.mend.io/api/mc/badges/adoption/npm/@typespec%2fopenapi3/0.63.0?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![passing](https://developer.mend.io/api/mc/badges/compatibility/npm/@typespec%2fopenapi3/0.62.0/0.63.0?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![confidence](https://developer.mend.io/api/mc/badges/confidence/npm/@typespec%2fopenapi3/0.62.0/0.63.0?slim=true)](https://docs.renovatebot.com/merge-confidence/)
| peerDependencies | minor |
| [@typespec/versioning](https://typespec.io)
([source](https://redirect.github.com/microsoft/typespec)) | [`^0.62.0`
->
`^0.63.0`](https://renovatebot.com/diffs/npm/@typespec%2fversioning/0.62.0/0.63.0)
|
[![age](https://developer.mend.io/api/mc/badges/age/npm/@typespec%2fversioning/0.63.0?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![adoption](https://developer.mend.io/api/mc/badges/adoption/npm/@typespec%2fversioning/0.63.0?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![passing](https://developer.mend.io/api/mc/badges/compatibility/npm/@typespec%2fversioning/0.62.0/0.63.0?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![confidence](https://developer.mend.io/api/mc/badges/confidence/npm/@typespec%2fversioning/0.62.0/0.63.0?slim=true)](https://docs.renovatebot.com/merge-confidence/)
| peerDependencies | minor |
| [commander](https://redirect.github.com/tj/commander.js) | [`^12.1.0`
-> `^13.0.0`](https://renovatebot.com/diffs/npm/commander/12.1.0/13.0.0)
|
[![age](https://developer.mend.io/api/mc/badges/age/npm/commander/13.0.0?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![adoption](https://developer.mend.io/api/mc/badges/adoption/npm/commander/13.0.0?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![passing](https://developer.mend.io/api/mc/badges/compatibility/npm/commander/12.1.0/13.0.0?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![confidence](https://developer.mend.io/api/mc/badges/confidence/npm/commander/12.1.0/13.0.0?slim=true)](https://docs.renovatebot.com/merge-confidence/)
| dependencies | major |
| [node](https://nodejs.org)
([source](https://redirect.github.com/nodejs/node)) | `22.11.0` ->
`22.12.0` |
[![age](https://developer.mend.io/api/mc/badges/age/node-version/node/v22.12.0?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![adoption](https://developer.mend.io/api/mc/badges/adoption/node-version/node/v22.12.0?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![passing](https://developer.mend.io/api/mc/badges/compatibility/node-version/node/v22.11.0/v22.12.0?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![confidence](https://developer.mend.io/api/mc/badges/confidence/node-version/node/v22.11.0/v22.12.0?slim=true)](https://docs.renovatebot.com/merge-confidence/)
| | minor |
| [yarn](https://redirect.github.com/yarnpkg/berry)
([source](https://redirect.github.com/yarnpkg/berry/tree/HEAD/packages/yarnpkg-cli))
| [`4.5.3` ->
`4.6.0`](https://renovatebot.com/diffs/npm/yarn/4.5.3/4.6.0) |
[![age](https://developer.mend.io/api/mc/badges/age/npm/@yarnpkg%2fcli/4.6.0?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![adoption](https://developer.mend.io/api/mc/badges/adoption/npm/@yarnpkg%2fcli/4.6.0?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![passing](https://developer.mend.io/api/mc/badges/compatibility/npm/@yarnpkg%2fcli/4.5.3/4.6.0?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![confidence](https://developer.mend.io/api/mc/badges/confidence/npm/@yarnpkg%2fcli/4.5.3/4.6.0?slim=true)](https://docs.renovatebot.com/merge-confidence/)
| packageManager | minor |

---

### Release Notes

<details>
<summary>commander-js/extra-typings
(@&#8203;commander-js/extra-typings)</summary>

###
[`v13.0.0`](https://redirect.github.com/commander-js/extra-typings/blob/HEAD/CHANGELOG.md#1300-2024-12-31)

[Compare
Source](https://redirect.github.com/commander-js/extra-typings/compare/v12.1.0...v13.0.0)

##### Added

- strongly type `.optsWithGlobals()` to include inferred globals
(\[[#&#8203;78](https://redirect.github.com/commander-js/extra-typings/issues/78)])
- weakly type `.getOptionValueSourceWithGlobals()` to include inferred
globals
(\[[#&#8203;78](https://redirect.github.com/commander-js/extra-typings/issues/78)])
- infer narrow types for choices, so no longer need to specify as
`const`
(\[[#&#8203;79](https://redirect.github.com/commander-js/extra-typings/issues/79)])

##### Changed

- *Breaking:* Typescript 5.0 or higher is required
(\[[#&#8203;79](https://redirect.github.com/commander-js/extra-typings/issues/79)])

</details>

<details>
<summary>tj/commander.js (commander)</summary>

###
[`v13.0.0`](https://redirect.github.com/tj/commander.js/blob/HEAD/CHANGELOG.md#1300-2024-12-30)

[Compare
Source](https://redirect.github.com/tj/commander.js/compare/v12.1.0...v13.0.0)

##### Added

- support multiple calls to `.parse()` with default settings
(\[[#&#8203;2299](https://redirect.github.com/tj/commander.js/issues/2299)])
- add `.saveStateBeforeParse()` and `.restoreStateBeforeParse()` for use
by subclasses
(\[[#&#8203;2299](https://redirect.github.com/tj/commander.js/issues/2299)])
- style routines like `styleTitle()` to add color to help using
`.configureHelp()` or Help subclass
(\[[#&#8203;2251](https://redirect.github.com/tj/commander.js/issues/2251)])
- color related support in `.configureOutput()` for `getOutHasColors()`,
`getErrHasColors()`, and `stripColor()`
(\[[#&#8203;2251](https://redirect.github.com/tj/commander.js/issues/2251)])
- Help property for `minWidthToWrap`
(\[[#&#8203;2251](https://redirect.github.com/tj/commander.js/issues/2251)])
- Help methods for `displayWidth()`, `boxWrap()`, `preformatted()` et al
(\[[#&#8203;2251](https://redirect.github.com/tj/commander.js/issues/2251)])

##### Changed

- *Breaking*: excess command-arguments cause an error by default, see
migration tips
(\[[#&#8203;2223](https://redirect.github.com/tj/commander.js/issues/2223)])
- *Breaking*: throw during Option construction for unsupported option
flags, like multiple characters after single `-`
(\[[#&#8203;2270](https://redirect.github.com/tj/commander.js/issues/2270)])
- *Breaking*: throw on multiple calls to `.parse()` if
`storeOptionsAsProperties: true`
(\[[#&#8203;2299](https://redirect.github.com/tj/commander.js/issues/2299)])
- TypeScript: include implicit `this` in parameters for action handler
callback
(\[[#&#8203;2197](https://redirect.github.com/tj/commander.js/issues/2197)])

##### Deleted

- *Breaking*: `Help.wrap()` refactored into `formatItem()` and
`boxWrap()`
(\[[#&#8203;2251](https://redirect.github.com/tj/commander.js/issues/2251)])

##### Migration Tips

**Excess command-arguments**

It is now an error for the user to specify more command-arguments than
are expected. (`allowExcessArguments` is now false by default.)

Old code:

```js
program.option('-p, --port <number>', 'port number');
program.action((options) => {
  console.log(program.args);
});
```

Now shows an error:

```console
$ node example.js a b c
error: too many arguments. Expected 0 arguments but got 3.
```

You can declare the expected arguments. The help will then be more
accurate too. Note that declaring
new arguments will change what is passed to the action handler.

```js
program.option('-p, --port <number>', 'port number');
program.argument('[args...]', 'remote command and arguments'); // expecting zero or more arguments
program.action((args, options) => {
  console.log(args);
});
```

Or you could suppress the error, useful for minimising changes in legacy
code.

```js
program.option('-p, --port', 'port number');
program.allowExcessArguments();
program.action((options) => {
  console.log(program.args);
});
```

</details>

<details>
<summary>nodejs/node (node)</summary>

###
[`v22.12.0`](https://redirect.github.com/nodejs/node/compare/v22.11.0...v22.12.0)

[Compare
Source](https://redirect.github.com/nodejs/node/compare/v22.11.0...v22.12.0)

</details>

<details>
<summary>yarnpkg/berry (yarn)</summary>

###
[`v4.6.0`](https://redirect.github.com/yarnpkg/berry/compare/2fe7d635e8eb163c1b3e56ab76e652b6bae8c160...1871484db82161065ac437d4df59bc8a4f94a33e)

[Compare
Source](https://redirect.github.com/yarnpkg/berry/compare/2fe7d635e8eb163c1b3e56ab76e652b6bae8c160...1871484db82161065ac437d4df59bc8a4f94a33e)

</details>

---

### Configuration

📅 **Schedule**: Branch creation - "* 0-3 1 * *" (UTC), Automerge - At
any time (no schedule defined).

🚦 **Automerge**: Disabled by config. Please merge this manually once you
are satisfied.

♻ **Rebasing**: Whenever PR is behind base branch, or you tick the
rebase/retry checkbox.

👻 **Immortal**: This PR will be recreated if closed unmerged. Get
[config
help](https://redirect.github.com/renovatebot/renovate/discussions) if
that's undesired.

---

- [ ] <!-- rebase-check -->If you want to rebase/retry this PR, check
this box

---

This PR was generated by [Mend Renovate](https://mend.io/renovate/).
View the [repository job
log](https://developer.mend.io/github/mnahkies/openapi-code-generator).

<!--renovate-debug:eyJjcmVhdGVkSW5WZXIiOiIzOS44NS4wIiwidXBkYXRlZEluVmVyIjoiMzkuODUuMCIsInRhcmdldEJyYW5jaCI6Im1haW4iLCJsYWJlbHMiOltdfQ==-->

Co-authored-by: renovate[bot] <29139614+renovate[bot]@users.noreply.github.com>